function createYMLFile(directory: text, yaml: text, usageSeperator: string = "||", listSeperator: string = ";"):
  load yaml {_directory} as {_directory}
  loop split {_yaml} at {_usageSeperator}:
    if loop-value parsed as "val[ue]: %text%:%text%" is set:
      set {_values::*} to loop-value parsed as "val[ue]:[ ]%text%:%text%"
      set skript-yaml value {_values::1} from {_directory} to {_values::2}
    else if loop-value parsed as "l[i]st:[ ]%text%:%text%" is set:
      set {_values::*} to loop-value parsed as "l[i]st:[ ]%text%:%text%"
      set skript-yaml list {_values::1} to split {_values::2} at {_listSeperator}
  save yaml {_directory}